name: Publish to NPM

on:
  release:
    types: [published]
  workflow_dispatch:
    inputs:
      version:
        description: 'Version to publish (e.g., patch, minor, major, skip, or specific version)'
        required: true
        default: 'patch'
      tag:
        description: 'NPM tag (e.g., latest, beta, next)'
        required: true
        default: 'latest'

jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      id-token: write
      
    steps:
    - uses: actions/checkout@v4
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        
    - name: Configure Git
      run: |
        git config --global user.name "GitHub Actions"
        git config --global user.email "actions@github.com"
        
    - name: Use Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20.x'
        registry-url: 'https://registry.npmjs.org'
        cache: 'npm'
        
    - name: Install FFmpeg
      run: |
        sudo apt-get update
        sudo apt-get install -y ffmpeg
        
    - name: Install dependencies
      run: npm ci
      
    - name: Run tests
      run: npm test -- --ci --passWithNoTests
      env:
        CI: true
        
    - name: Build
      run: npm run build
      
    - name: Lint
      run: npm run lint
      
    - name: Version bump (manual trigger)
      if: github.event_name == 'workflow_dispatch' && github.event.inputs.version != 'skip'
      run: |
        npm version ${{ github.event.inputs.version }} --no-git-tag-version
        VERSION=$(node -p "require('./package.json').version")
        git add package.json package-lock.json
        git commit -m "chore: bump version to v$VERSION [skip ci]"
        git tag "v$VERSION"
        git push origin main --tags
        
    - name: Publish to NPM
      run: |
        if [ "${{ github.event_name }}" == "workflow_dispatch" ]; then
          npm publish --tag ${{ github.event.inputs.tag }}
        else
          npm publish
        fi
      env:
        NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
        
    - name: Create GitHub Release (manual trigger)
      if: github.event_name == 'workflow_dispatch'
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: v${{ steps.version.outputs.version }}
        release_name: Release v${{ steps.version.outputs.version }}
        body: |
          ## Changes in this Release
          
          ### Features
          - Distributed transcoding support for Kubernetes deployments
          - Redis-based coordination for multi-node processing
          - Automatic fallback from distributed to local mode
          - Configurable TTLs and timeouts
          
          ### Bug Fixes
          - Fixed async promise executor anti-pattern
          - Replaced synchronous file operations with async versions
          - Fixed singleton concurrency issues
          - Improved resource cleanup and error handling
          
          ### Performance Improvements
          - Atomic file operations prevent race conditions
          - Optimized file polling mechanisms
          - Better type safety throughout
          
          See [CHANGELOG.md](https://github.com/eleven-am/transcoder/blob/main/CHANGELOG.md) for detailed changes.
        draft: false
        prerelease: ${{ github.event.inputs.tag != 'latest' }}